const fs = require('fs')
let c = fs.readFileSync('mod-panel/app.js', 'utf8')
c = c.replace("No tenés cartas aún. ¡Abrí un sobre!", "No tienes cartas aún. ¡Abre un sobre!")
c = c.replace("No tenés suficientes puntos. Necesitás", "No tienes suficientes puntos. Necesitas")
c = c.replace("Este canal no tiene cartas configuradas aún.", "Este canal no tiene cartas configuradas aún.")
c = c.replace("Conectá Twitch primero", "Conecta Twitch primero")
c = c.replace("¡Abrí un sobre!", "¡Abre un sobre!")
fs.writeFileSync('mod-panel/app.js', c)
console.log('fixed')
